# .github/workflows/codecov-test-suites.yml

name: Run Test Suites

on: [push]

jobs:
  test-dataforecasting:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: DataForecasting
    steps:
      - uses: actions/checkout@v2
      #Test python code
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          python -m pytest
      - name :  pushing to codecov
        run: bash <(curl -s https://codecov.io/bash) # Upload to Codecov
        
  test-ip_server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ImageProcessing/Combination/API_server
    steps:
      - uses: actions/checkout@v2
      #Test go code
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Build Go
        run: go build .
      - name: Test Go
        run: go test -v .
      - name :  pushing to codecov
        run: bash <(curl -s https://codecov.io/bash) # Upload to Codecov
